name: Rhythmic Epistles
description: 欲買桂花同載酒，終不似，少年遊。
url: https://kakack.github.io
#baseurl: /blog
avatar: https://raw.githubusercontent.com/kakack/kakack.github.io/master/_images/logo.jpg
favicon: https://raw.githubusercontent.com/kakack/kakack.github.io/master/_images/icon.jpg
navigation:
  - name: Main
    url: /
  - name: About
    url: /about
  - name: Archive
    url: /archive
  - name: Tags
    url: /tags
paginate: 8
excerpt_separator: <!-- more -->
footer-links: 
  email: kakachen1990@gmail.com
  github: kakack
  instagram: kakack90
  linkedin: kakack
footer-text: Copyright (c) 2023 Let's talk with the world.
disqus: kakack 

# gitalk:
#   clientID: 
#   clientSecret: 
#   repo: 
#   owner: 
#   proxy:
google_analytics:
utteranc:
  repo: https://github.com/kakack/kakack.github.io
permalink: /:title/
paginate_path: /page:num/
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
  math_engine: mathjax

sass:
  style: :expanded # You might prefer to minify using :compressed
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate
  - jekyll-gist
  - jekyll-remote-theme
  - jekyll-scholar
  - jekyll-katex
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

