markdown: kramdown
permalink: /:year/:month/:title/
author: Kaka Chen	
pygments: true
paginate: 16
url: http://kakack.github.io
baseurl: /
encoding: utf-8
highlighter: rouge
name: What a DREAMY Journey
favicon: "_images/favicon.png"
open_in_new: true
highlightStyle: xcode
